services:
  flantastic:
    build:
      context: flantastic
      dockerfile: Dockerfile
    container_name: flantastic
    tty: true
    restart: unless-stopped

  llama-cpp:
    build:
      context: ./llama.cpp/
      dockerfile: .devops/full.Dockerfile
    volumes:
      - ./data:/data
    container_name: llama-cpp
    tty: true
    restart: unless-stopped
    environment:
      - "HUGGINGFACE_MODEL=Qwen/Qwen2.5-0.5B-Instruct"
    entrypoint: /data/entrypoint.sh

  open-webui:
    build:
      context: ./open-webui
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - llama-cpp
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_AUTH=false'
      - 'OLLAMA_BASE_URL=http://flantastic:11434'
      - 'DEFAULT_MODELS=/data/models/Qwen2.5-0.5B-Instruct.gguf'
      - 'ENABLE_OAUTH_SIGNUP=false'
      - 'WEBUI_SECRET_KEY='
      - 'ENABLE_OPENAI_API=true'
      - 'OPENAI_API_BASE_URL=http://llama-cpp:8081/v1'
      - 'OPENAI_API_KEY=none'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}